name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    # 1. Levantar el servicio de PostgreSQL en el Runner
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testqaUser
          POSTGRES_PASSWORD: QAUser
          POSTGRES_DB: pixel_arcade
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Instalar cliente de PostgreSQL
      run: sudo apt-get update && sudo apt-get install -y postgresql-client

    - name: Poblar base de datos con el script de Pixel Arcade
      run: psql -h localhost -U testqaUser -d pixel_arcade -f setup.sql
      env:
        PGPASSWORD: QAUser

    - name: Run Playwright tests
      run: npx playwright test
      env:
        # Variables para que Playwright se conecte a la BD del runner
        DB_HOST: localhost
        DB_PORT: 5432
        DB_USER: testqaUser
        DB_PASSWORD: QAUser
        DB_NAME: pixel_arcade

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    